#! /bin/bash
function connect_to_db() {
  HOST=$(docker inspect $(docker container ls --format "{{.Names}}" | fzf | xargs echo) | jq '.[0].NetworkSettings.Networks.[].IPAddress' -r | xargs echo -n )
  CONN_STR="INSERT_DEFAULT"
  rainfrog -u $CONN_STR
}
